// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig } from "prisma/config"

function deriveSupabaseDirectUrl(databaseUrl: string | undefined) {
  if (!databaseUrl) {
    return undefined
  }

  try {
    const parsed = new URL(databaseUrl)

    // Supabase Prisma guidance uses transaction mode (6543) for runtime and
    // session/direct mode (5432) for migrations. Prisma 7 no longer accepts
    // directUrl in prisma.config.ts, so we make DIRECT_URL available here.
    if (parsed.hostname.endsWith(".pooler.supabase.com") && parsed.port === "6543") {
      parsed.port = "5432"
      parsed.searchParams.delete("pgbouncer")
      return parsed.toString()
    }

    parsed.searchParams.delete("pgbouncer")
    return parsed.toString()
  } catch {
    return undefined
  }
}

if (!process.env.DIRECT_URL) {
  const derivedDirectUrl = deriveSupabaseDirectUrl(process.env.DATABASE_URL)

  if (derivedDirectUrl) {
    process.env.DIRECT_URL = derivedDirectUrl
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI commands should use a direct/session connection for migrations.
    url:
      process.env.DIRECT_URL ??
      deriveSupabaseDirectUrl(process.env.DATABASE_URL) ??
      process.env.DATABASE_URL ??
      "",
  },
})
